from __future__ import annotations

# ruff: noqa: F401, I001
from codeseam.analysis.assessment.definitions import (
    REVIEW_TIERS,
    FindingActionStatus,
    FindingReviewVisibility,
    FindingVisibility,
    ReviewTier,
)
from codeseam.analysis.repository import (
    FileRecord,
    RepositoryFacts,
    RepositoryManifest,
    RepositoryScan,
    build_repository_facts,
    repository_facts_cache_value,
    repository_facts_from_cache_value,
)
from codeseam.analysis.repository.classification import classify_path
from codeseam.analysis.repository.languages import detect_language, is_analysis_language
from codeseam.analysis.signatures import (
    AdapterId,
    BoundarySpecificity,
    CalleeShape,
    CallFingerprint,
    CallsitePattern,
    DataflowEdge,
    DataflowGraph,
    DataflowNode,
    DuplicateBlockCandidate,
    ExpressionShape,
    IntraFunctionDuplicateBlock,
    LanguageFamily,
    NORMALIZATION_TRANSFORM_METHODS,
    ParameterUseVector,
    PolicyConstant,
    SignatureAnalysis,
    SignatureAnalysisFeatures,
    SignatureBodySummary,
    SignatureCore,
    SignatureIdentity,
    SignatureOutputDetail,
    SignatureRecord,
    SignatureShape,
    SignatureTypeClass,
    SignatureTypeSource,
    adapter_id,
    call_kwarg_shape_values,
    canonical_shape,
    classify_signature_type,
    collection_element_type_class,
    duplicate_block_bounds_ok,
    duplicate_block_candidate,
    duplicate_blocks_from_candidates,
    language_family,
    signature_analysis_from_core,
    signature_analysis_from_record,
    signature_analysis_key,
    signature_core_from_record,
)
from codeseam.analysis.semantic_roles import (
    API_SURFACE_ROLES,
    INTERFACE_ONLY_ROLES,
    FunctionSemanticRole,
    FunctionSemanticRoles,
    PathSemanticRoleOptions,
    async_path,
    has_common_test_path_part,
    path_semantic_roles,
    sync_async_mirror_members,
    sync_async_mirror_pair,
)
from codeseam.analysis.inventory.ir import FunctionIR, ParamIR, signature_shape
from codeseam.analysis.inventory.model import (
    FileWithoutFunctionUnits,
    FunctionInventory,
    FunctionRecord,
    assign_ids,
    function_cache_payload,
    functions_from_cache_value,
)
from codeseam.analysis.relations import (
    AbstractionKind,
    ActionKind,
    CloneClass,
    EvidenceKind,
    RelationKind,
    candidates,
    ordered_tree_edit_distance,
    pairs,
    similarity,
)
from codeseam.analysis.signatures import OrderedTree, ordered_tree_size
from codeseam.analysis.relations.models import (
    AbstractionCostComponents,
    ActionStatus,
    ArgumentNormalization,
    CachedRelationSummary,
    CloneClassification,
    DeltaKind,
    MemberFeatureCache,
    MemberFeatures,
    MemberInput,
    MemberRef,
    PairActionInput,
    RefactorabilityComponents,
    RefactorAction,
    RefactorShape,
    RelationBasis,
    RelationFlags,
    RelationMember,
    RelationMemberContext,
    RelationPair,
    RelationScores,
    ScoreBand,
    SequenceComparison,
    SimilarityScores,
    TreeComparison,
    sequence_skeleton_summary,
)
from codeseam.analysis.relations.policy import (
    PAIR_POLICY,
    RELATION_ASSESSMENT_POLICY,
    TREE_EDIT_POLICY,
)
from codeseam.analysis.relations.unification import (
    ROLE_STATEMENT_SEQUENCE_DELTA,
    SequenceSkeleton,
    SequenceTemplateItem,
    anti_unify_sequences,
    anti_unify_trees,
)
from codeseam.analysis.relations.actions import pair_actions
from codeseam.analysis.relations.callables import callsite_evidence_kinds, is_callable_return
from codeseam.analysis.relations.enrichment import RelationPairBuilder
from codeseam.analysis.relations.features import member_features
from codeseam.analysis.relations.normalization import (
    argument_normalization_relation_features,
    has_argument_normalization_transform,
    shared_operation_candidate,
)
from codeseam.analysis.relations.pairs import (
    ActionBuilder,
    TreeEditBudget,
    feature_member_ref,
    relation_pair_from_features,
)
from codeseam.analysis.relations.risks import is_test_member, layer_path
from codeseam.analysis.relations.shapes import abstraction_estimate
from codeseam.analysis.relations.shingles import structural_shingles
from codeseam.analysis.relations.similarity import tree_comparison_features
from codeseam.analysis.assessment import (
    AbstractionFit,
    AbstractionRisk,
    ActionAssessment,
    AssessmentBand,
    AssessmentBreakdown,
    AssessmentGate,
    AssessmentPolicy,
    ContextClassification,
    DetectionConfidence,
    DetectionPolicy,
    EvidenceQuality,
    EvidenceStrength,
    EvidenceSummary,
    ExtractionConfidence,
    MaintenancePayoff,
    RecommendationCap,
    RecommendationStatus,
    SemanticRisk,
    build_findings,
)
from codeseam.analysis.assessment.action import action_status_for, recommend_action
from codeseam.analysis.assessment.assess import assess_target
from codeseam.analysis.assessment.cluster import (
    CandidateGenerationSummary,
    Cluster,
    ClusterEnrichment,
    ClusterMember,
    Clusters,
    ClusterSummary,
    PolicyConstantCluster,
    StructuralSubcluster,
)
from codeseam.analysis.assessment.cluster.build import build_clusters
from codeseam.analysis.assessment.cluster.policy_constants import build_policy_constant_clusters
from codeseam.analysis.assessment.context import classify_contexts
from codeseam.analysis.assessment.detection import score_detection_confidence
from codeseam.analysis.assessment.evidence import (
    EVIDENCE_ANTI_UNIFICATION_TEMPLATE,
    EVIDENCE_ARGUMENT_NORMALIZATION_WRAPPER,
    EVIDENCE_CALL_FINGERPRINT_OVERLAP,
    EVIDENCE_CONTROL_CONTEXT_SIMILARITY,
    evidence_summary,
)
from codeseam.analysis.assessment.fit import score_abstraction_fit
from codeseam.analysis.assessment.payoff import score_maintenance_payoff
from codeseam.analysis.assessment.risk import score_semantic_risk
from codeseam.analysis.assessment.semantic_caps import (
    SemanticCapAssessment,
    apply_semantic_cap,
    semantic_cap_for,
)
from codeseam.analysis.findings import (
    EvidenceItem,
    Finding,
    FindingDecision,
    FindingDraft,
    FindingLocation,
    FindingMetrics,
    FindingTargetType,
    SemanticEvidenceMetrics,
)
from codeseam.analysis.findings.drafts import (
    _promotable_exact_pairs,
    _should_promote_structural_pairs,
    _structural_metrics,
    _sync_async_member_pair,
)
from codeseam.analysis.findings.identity import primary_action
from codeseam.analysis.findings.review import review_tier_counts
from codeseam.analysis.findings.semantic_evidence import SemanticEvidenceIndex

__all__ = [
    "API_SURFACE_ROLES",
    "AbstractionCostComponents",
    "AbstractionFit",
    "AbstractionKind",
    "AbstractionRisk",
    "ActionAssessment",
    "ActionBuilder",
    "ActionKind",
    "ActionStatus",
    "AdapterId",
    "ArgumentNormalization",
    "AssessmentBand",
    "AssessmentBreakdown",
    "AssessmentGate",
    "AssessmentPolicy",
    "BoundarySpecificity",
    "CachedRelationSummary",
    "CallFingerprint",
    "CalleeShape",
    "CallsitePattern",
    "CandidateGenerationSummary",
    "CloneClass",
    "CloneClassification",
    "Cluster",
    "ClusterEnrichment",
    "ClusterMember",
    "ClusterSummary",
    "Clusters",
    "ContextClassification",
    "DataflowEdge",
    "DataflowGraph",
    "DataflowNode",
    "DeltaKind",
    "DetectionConfidence",
    "DetectionPolicy",
    "DuplicateBlockCandidate",
    "EVIDENCE_ANTI_UNIFICATION_TEMPLATE",
    "EVIDENCE_ARGUMENT_NORMALIZATION_WRAPPER",
    "EVIDENCE_CALL_FINGERPRINT_OVERLAP",
    "EVIDENCE_CONTROL_CONTEXT_SIMILARITY",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceQuality",
    "EvidenceStrength",
    "EvidenceSummary",
    "ExpressionShape",
    "ExtractionConfidence",
    "FileRecord",
    "Finding",
    "FindingActionStatus",
    "FindingDecision",
    "FindingDraft",
    "FindingLocation",
    "FindingMetrics",
    "FindingReviewVisibility",
    "FindingTargetType",
    "FindingVisibility",
    "FunctionIR",
    "FunctionInventory",
    "FunctionRecord",
    "FunctionSemanticRole",
    "FunctionSemanticRoles",
    "FileWithoutFunctionUnits",
    "INTERFACE_ONLY_ROLES",
    "IntraFunctionDuplicateBlock",
    "LanguageFamily",
    "MaintenancePayoff",
    "MemberFeatureCache",
    "MemberFeatures",
    "MemberInput",
    "MemberRef",
    "NORMALIZATION_TRANSFORM_METHODS",
    "OrderedTree",
    "PAIR_POLICY",
    "ParamIR",
    "ParameterUseVector",
    "PathSemanticRoleOptions",
    "PolicyConstant",
    "PolicyConstantCluster",
    "RELATION_ASSESSMENT_POLICY",
    "REVIEW_TIERS",
    "ROLE_STATEMENT_SEQUENCE_DELTA",
    "RecommendationCap",
    "RecommendationStatus",
    "RefactorAction",
    "RefactorShape",
    "RefactorabilityComponents",
    "RelationBasis",
    "RelationFlags",
    "RelationKind",
    "RelationMember",
    "RelationMemberContext",
    "RelationPair",
    "RelationPairBuilder",
    "RelationScores",
    "RepositoryFacts",
    "RepositoryManifest",
    "RepositoryScan",
    "ReviewTier",
    "ScoreBand",
    "SemanticCapAssessment",
    "SemanticEvidenceIndex",
    "SemanticEvidenceMetrics",
    "SemanticRisk",
    "SequenceComparison",
    "SequenceSkeleton",
    "SequenceTemplateItem",
    "SignatureAnalysis",
    "SignatureAnalysisFeatures",
    "SignatureBodySummary",
    "SignatureCore",
    "SignatureIdentity",
    "SignatureOutputDetail",
    "SignatureRecord",
    "SignatureShape",
    "SignatureTypeClass",
    "SignatureTypeSource",
    "SimilarityScores",
    "StructuralSubcluster",
    "TREE_EDIT_POLICY",
    "TreeComparison",
    "TreeEditBudget",
    "call_kwarg_shape_values",
    "_promotable_exact_pairs",
    "_should_promote_structural_pairs",
    "_structural_metrics",
    "_sync_async_member_pair",
    "abstraction_estimate",
    "action_status_for",
    "adapter_id",
    "anti_unify_sequences",
    "anti_unify_trees",
    "apply_semantic_cap",
    "argument_normalization_relation_features",
    "assess_target",
    "async_path",
    "assign_ids",
    "build_clusters",
    "build_findings",
    "build_policy_constant_clusters",
    "build_repository_facts",
    "callsite_evidence_kinds",
    "candidates",
    "canonical_shape",
    "classify_contexts",
    "classify_path",
    "classify_signature_type",
    "collection_element_type_class",
    "detect_language",
    "duplicate_block_bounds_ok",
    "duplicate_block_candidate",
    "duplicate_blocks_from_candidates",
    "evidence_summary",
    "feature_member_ref",
    "function_cache_payload",
    "functions_from_cache_value",
    "has_argument_normalization_transform",
    "has_common_test_path_part",
    "is_analysis_language",
    "is_callable_return",
    "is_test_member",
    "language_family",
    "layer_path",
    "member_features",
    "ordered_tree_edit_distance",
    "ordered_tree_size",
    "PairActionInput",
    "pair_actions",
    "pairs",
    "path_semantic_roles",
    "primary_action",
    "recommend_action",
    "relation_pair_from_features",
    "repository_facts_cache_value",
    "repository_facts_from_cache_value",
    "review_tier_counts",
    "score_abstraction_fit",
    "score_detection_confidence",
    "score_maintenance_payoff",
    "score_semantic_risk",
    "semantic_cap_for",
    "sequence_skeleton_summary",
    "shared_operation_candidate",
    "signature_analysis_from_core",
    "signature_analysis_from_record",
    "signature_analysis_key",
    "signature_core_from_record",
    "signature_shape",
    "similarity",
    "structural_shingles",
    "sync_async_mirror_members",
    "sync_async_mirror_pair",
    "tree_comparison_features",
]
