from __future__ import annotations

from dataclasses import dataclass, field

BOUNDARY_TOKENS = {
    "auth",
    "crypto",
    "fast",
    "latency",
    "perf",
    "sanitize",
    "secret",
    "security",
    "timeout",
}


@dataclass(frozen=True, slots=True)
class StructuralPolicy:
    """Limits for cluster-level structural enrichment before pair scoring."""

    summary_limit: int = field(
        default=5,
        metadata={"doc": "Maximum representative items shown in relation summaries."},
    )
    structural_pair_limit: int = field(
        default=10,
        metadata={
            "doc": "Maximum high-confidence structural duplicate pairs retained per cluster."
        },
    )
    structural_cluster_member_limit: int = field(
        default=80,
        metadata={
            "doc": "Maximum members enriched normally before broad-cluster safeguards apply."
        },
    )
    structural_bucket_member_limit: int = field(
        default=32,
        metadata={"doc": "Maximum members allowed in a bounded structural candidate bucket."},
    )
    structural_pair_candidate_limit: int = field(
        default=400,
        metadata={"doc": "Maximum candidate pairs generated by deterministic structural buckets."},
    )
    max_statement_count: int = field(
        default=8,
        metadata={
            "doc": "Largest compact statement sequence eligible for exact structural matching."
        },
    )
    max_tree_nodes: int = field(
        default=120,
        metadata={"doc": "Largest body-tree node count eligible for tree-edit comparison."},
    )
    name_similarity_threshold: float = field(
        default=0.85,
        metadata={"doc": "Name similarity needed to classify a strong structural duplicate."},
    )
    tree_similarity_threshold: float = field(
        default=0.9,
        metadata={"doc": "Tree similarity needed to classify a strong structural duplicate."},
    )


@dataclass(frozen=True, slots=True)
class TreeEditPolicy:
    """Gates and budgets for expensive ordered tree-edit comparisons."""

    name_threshold: float = field(
        default=0.85,
        metadata={"doc": "Name similarity that makes tree-edit comparison worth considering."},
    )
    sequence_threshold: float = field(
        default=0.75,
        metadata={"doc": "Statement-sequence similarity sufficient to request tree-edit evidence."},
    )
    call_threshold: float = field(
        default=0.65,
        metadata={"doc": "Call multiset similarity used with call_sequence_threshold."},
    )
    graph_threshold: float = field(
        default=0.60,
        metadata={"doc": "Compact dataflow similarity used with graph_sequence_threshold."},
    )
    call_sequence_threshold: float = field(
        default=0.40,
        metadata={"doc": "Minimum sequence similarity when call similarity is the main tree gate."},
    )
    graph_sequence_threshold: float = field(
        default=0.30,
        metadata={
            "doc": "Minimum sequence similarity when graph similarity is the main tree gate."
        },
    )
    cluster_budget: int = field(
        default=8,
        metadata={"doc": "Maximum requested tree edits per cluster before proxy scoring is used."},
    )
    run_budget: int = field(
        default=32,
        metadata={"doc": "Default total tree-edit budget shared by one relation scoring run."},
    )
    edit_product_limit: int = field(
        default=20_000,
        metadata={"doc": "Maximum left_nodes * right_nodes product for exact tree edit distance."},
    )


@dataclass(frozen=True, slots=True)
class PairPolicy:
    """Pair-level relation scoring thresholds.

    These values decide whether a candidate pair becomes a relation and how
    small special relation families are lifted above generic similarity scores.
    """

    relation_pair_limit: int = field(
        default=20,
        metadata={"doc": "Maximum relation pairs emitted per enriched signature cluster."},
    )
    relatedness_minimum: float = field(
        default=0.35,
        metadata={"doc": "Minimum final relatedness score required to emit a relation pair."},
    )
    parameter_flow_threshold: float = field(
        default=0.85,
        metadata={"doc": "Parameter-use similarity treated as matching argument flow."},
    )
    min_wrapper_stable_edge_count: int = field(
        default=3,
        metadata={"doc": "Minimum stable prefix+suffix statements for wrapper/core evidence."},
    )
    min_argument_normalization_relatedness: float = field(
        default=0.72,
        metadata={
            "doc": (
                "Relatedness floor for argument-normalization wrappers: pairs that normalize "
                "different inputs before the same downstream operation should not be ranked as "
                "weak merely because their signatures differ."
            )
        },
    )
    min_argument_normalization_refactorability: float = field(
        default=0.68,
        metadata={
            "doc": (
                "Refactorability floor for argument-normalization wrappers when the downstream "
                "operation is shared and the remaining differences are mostly argument binding."
            )
        },
    )
    name_gate_token_similarity_threshold: float = field(
        default=0.5,
        metadata={
            "doc": (
                "Token-overlap threshold before paying for string edit distance in name scoring; "
                "below this, token Jaccard is used as the cheap name score."
            )
        },
    )
    multi_member_threshold: int = field(
        default=2,
        metadata={
            "doc": "Minimum member count that turns pair evidence into a group-level action."
        },
    )
    action_limit: int = field(
        default=5,
        metadata={"doc": "Maximum refactor action candidates retained for a relation family."},
    )


@dataclass(frozen=True, slots=True)
class RelationAssessmentPolicy:
    """Risk and action thresholds used after pair relations have been scored."""

    high_abstraction_cost_threshold: float = field(
        default=0.65,
        metadata={"doc": "Cost score above which extraction is considered high-cost."},
    )
    manageable_parameter_count: int = field(
        default=2,
        metadata={"doc": "Parameter count still considered easy to extract or consolidate."},
    )
    high_parameter_count: int = field(
        default=6,
        metadata={"doc": "Parameter count that usually makes an abstraction cumbersome."},
    )
    parameterized_skeleton_max_abstraction_cost: float = field(
        default=0.25,
        metadata={
            "doc": (
                "Maximum abstraction cost before same-skeleton literal/callee variants stop "
                "emitting direct consolidate-clone action candidates."
            )
        },
    )
    refactorability_high_threshold: float = field(
        default=0.75,
        metadata={"doc": "Refactorability score band boundary for high-confidence editability."},
    )
    refactorability_medium_threshold: float = field(
        default=0.45,
        metadata={"doc": "Refactorability score band boundary for plausible editability."},
    )
    many_parameter_threshold: int = field(
        default=4,
        metadata={"doc": "Member parameter count that contributes an abstraction-risk caveat."},
    )
    min_vocabulary_members: int = field(
        default=2,
        metadata={"doc": "Minimum members needed before vocabulary mismatch is meaningful."},
    )


STRUCTURAL_POLICY = StructuralPolicy()
TREE_EDIT_POLICY = TreeEditPolicy()
PAIR_POLICY = PairPolicy()
RELATION_ASSESSMENT_POLICY = RelationAssessmentPolicy()

__all__ = [
    "BOUNDARY_TOKENS",
    "PAIR_POLICY",
    "RELATION_ASSESSMENT_POLICY",
    "STRUCTURAL_POLICY",
    "TREE_EDIT_POLICY",
    "PairPolicy",
    "RelationAssessmentPolicy",
    "StructuralPolicy",
    "TreeEditPolicy",
]
