from __future__ import annotations

from codeseam.analysis.signatures.duplicate_blocks import (
    DuplicateBlockCandidate,
    duplicate_block_bounds_ok,
    duplicate_block_candidate,
    duplicate_blocks_from_candidates,
)
from codeseam.analysis.signatures.metadata import (
    AdapterId,
    LanguageFamily,
    adapter_id,
    language_family,
)
from codeseam.analysis.signatures.model import (
    NORMALIZATION_TRANSFORM_METHODS,
    CalleeShape,
    CallFingerprint,
    CallsitePattern,
    DataflowEdge,
    DataflowGraph,
    DataflowNode,
    DuplicateBlockOccurrence,
    ExpressionShape,
    IntraFunctionDuplicateBlock,
    NormalizationLevel,
    ParameterUseVector,
    PolicyConstant,
    SignatureAnalysis,
    SignatureAnalysisFeatures,
    SignatureBodySummary,
    SignatureCore,
    SignatureIdentity,
    SignatureOutputDetail,
    SignatureRecord,
    SignatureShape,
    call_kwarg_shape_values,
    signature_analysis_from_core,
    signature_analysis_from_record,
    signature_analysis_key,
    signature_core_from_record,
)
from codeseam.analysis.signatures.shape import canonical_shape
from codeseam.analysis.signatures.tree import OrderedTree, ordered_tree_size
from codeseam.analysis.signatures.types import (
    BoundarySpecificity,
    SignatureTypeClass,
    SignatureTypeSource,
    classify_signature_type,
    collection_element_type_class,
)

__all__ = [
    "AdapterId",
    "BoundarySpecificity",
    "CallFingerprint",
    "CalleeShape",
    "CallsitePattern",
    "DataflowEdge",
    "DataflowGraph",
    "DataflowNode",
    "DuplicateBlockOccurrence",
    "DuplicateBlockCandidate",
    "ExpressionShape",
    "IntraFunctionDuplicateBlock",
    "LanguageFamily",
    "NORMALIZATION_TRANSFORM_METHODS",
    "NormalizationLevel",
    "OrderedTree",
    "ParameterUseVector",
    "PolicyConstant",
    "SignatureAnalysis",
    "SignatureAnalysisFeatures",
    "SignatureBodySummary",
    "SignatureCore",
    "SignatureIdentity",
    "SignatureOutputDetail",
    "SignatureRecord",
    "SignatureShape",
    "SignatureTypeClass",
    "SignatureTypeSource",
    "canonical_shape",
    "call_kwarg_shape_values",
    "adapter_id",
    "classify_signature_type",
    "collection_element_type_class",
    "language_family",
    "ordered_tree_size",
    "signature_analysis_key",
    "signature_analysis_from_core",
    "signature_analysis_from_record",
    "signature_core_from_record",
    "duplicate_blocks_from_candidates",
    "duplicate_block_candidate",
    "duplicate_block_bounds_ok",
]
